ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include("products.urls" , namespace="products"))
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path 
from . import views
app_name = "products"

urlpatterns = [

    path("home/" , views.Home , name="index") , 
    path("cart/" , views.cart , name="cart"),
    path("<int:id>/" ,  views.product_details , name="product_details"),
    path("delete/<int:id>/" ,  views.deleteProductFromCart , name="delete_product"),
    path("add/<int:id>/" ,  views.addToCart , name="add_product"),



    
]

ecommerce/products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
   image = models.ImageField()
   name = models.CharField(max_length=250)
   price = models.FloatField(default=0)
   alternatePrice = models.FloatField(default=0)
   rate = models.BigIntegerField()
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)
   desciption = models.TextField()
   def __str__(self):
      return self.name





class SelectedProducts(models.Model):
   image = models.ImageField()
   name = models.CharField(max_length=250)
   price = models.FloatField(default=0)
   qty = models.IntegerField(default=0)
   totalPrice = models.FloatField(default=0)
   def __str__(self):
      return self.name

ecommerce/products/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from django.http import Http404 
from .models import Product
from .models import SelectedProducts
def Home(request):
    products = Product.objects.all()
    return render(request ,"index.html" , {"products" : products})

def cart(request):
    cartProducts = SelectedProducts.objects.all()
    totalPrice = 0
    for product in cartProducts:
        totalPrice += product.totalPrice
    return render(request, "cart.html" , {"cartProdcuts" : cartProducts  , "totalPrice" : totalPrice})



def deleteProductFromCart(request , id):
    product = SelectedProducts.objects.get(id=id)
    product.delete()
    return redirect("products:cart")

def addToCart(request , id):
    product = Product.objects.get(id = id)
    SelectedProducts.objects.create(id = id , image = product.image , name=product.name , price = product.price , totalPrice = product.price * 1 , qty = 1 )
    return redirect("products:cart")


def product_details(request , id) :
    products = Product.objects.all()
    try:
        product = Product.objects.get(id = id)
    except:
        raise Http404("product not found")
    return render(request , "productDetails.html" ,{"products" : products  , "product" : product} )

ecommerce/products/templates/cart.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-[#F5F5F5]">
    {%include "components/header.html"%}


    <div class="overflow-x-auto p-[30px]">
        <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
            <thead class="ltr:text-left rtl:text-right">
                <tr>
                    <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Product</th>
                    <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Price</th>
                    <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Quntity</th>
                    <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Subtotal</th>
                    <th class="px-4 py-2"></th>
                </tr>
            </thead>

            <tbody class="divide-y divide-gray-200">
                {%block content%}
                {%for product in cartProdcuts%}
                <tr>
                    <td
                        class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 flex gap-[10px] items-center justify-center">

                        <img src="{{product.image.url}}" class="w-[40px] h-[40px]" alt="...">
                        <span>{{product.name}}</span>


                    </td>
                    <td class="whitespace-nowrap px-4 py-2 text-gray-700 text-center">${{product.price}}</td>
                    <td class="whitespace-nowrap px-4 py-2 text-gray-700 ">
                        <div class="flex justify-between items-center ">
                            <div class="w-[250px] max-w-sm relative m-auto ">
                                <div class="relative">
                                    <button id="decreaseButton"
                                        class="absolute right-9 top-1 rounded bg-slate-800 p-1.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
                                        type="button">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                            class="w-4 h-4">
                                            <path d="M3.75 7.25a.75.75 0 0 0 0 1.5h8.5a.75.75 0 0 0 0-1.5h-8.5Z" />
                                        </svg>
                                    </button>
                                    <input id="amountInput" type="number" value="{{product.qty}}"
                                        class="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md pl-3 pr-20 py-2 transition duration-300 ease focus:outline-none focus:border-slate-400 hover:border-slate-300 shadow-sm focus:shadow appearance-none [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none" />
                                    <button id="increaseButton"
                                        class="absolute right-1 top-1 rounded bg-slate-800 p-1.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
                                        type="button">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                            class="w-4 h-4">
                                            <path
                                                d="M8.75 3.75a.75.75 0 0 0-1.5 0v3.5h-3.5a.75.75 0 0 0 0 1.5h3.5v3.5a.75.75 0 0 0 1.5 0v-3.5h3.5a.75.75 0 0 0 0-1.5h-3.5v-3.5Z" />
                                        </svg>
                                    </button>
                                </div>

                            </div>

                            <script>
                                // Select the elements
                                const amountInput = document.getElementById('amountInput');
                                const increaseButton = document.getElementById('increaseButton');
                                const decreaseButton = document.getElementById('decreaseButton');

                                // Increase the value
                                increaseButton.addEventListener('click', () => {
                                    amountInput.value = parseInt(amountInput.value) + 1;
                                });

                                // Decrease the value and prevent going below 0
                                decreaseButton.addEventListener('click', () => {
                                    amountInput.value = Math.max(0, parseInt(amountInput.value) - 1);
                                });
                            </script>




                        </div>
                    </td>
                    <td class="whitespace-nowrap px-4 py-2 text-gray-700 text-center">${{product.totalPrice}}</td>
                    <td class="whitespace-nowrap px-4 py-2">
                        <a href="{%url 'products:delete_product' product.id %}"
                            class="inline-block rounded  text-[#DB4444]  px-4 py-2 text-xs font-medium text-white ">
                            <i class="fa-solid fa-trash text-[18px]"></i>
                        </a>
                    </td>
                </tr>
                {%endfor%}
                {%endblock%}
            </tbody>
        </table>
    </div>

    <div class="flex justify-between  flex-wrap ">
        <p class="py-[10px] px-[20px] text-white bg-[#DB4444] w-fit h-fit  float-end mt-[10px] mx-[30px]">
            <span>total price : </span> <span> {{totalPrice}}$</span>
        </p>

        <div class="border-[1px] border-solid border-black w-[300px] my-[10px] mx-[30px] ">
            <h2 class="p-[10px]">Cart Total</h2>
            <p class="flex justify-between border-b-[1px] border-solid border-[black] w-[300px] p-[10px]">
                <span>Shipping: </span>
                <span>free</span>
            </p>
            <p class="flex justify-between  w-[300px] p-[10px]">
                <span>Total: </span>
                <span>{{totalPrice}}$</span>
            </p>
        </div>

    </div>
</body>

</html>

ecommerce/products/templates/components/card.html
<div class="flex gap-[10px] m-[30px]">

    {% block content %}
    {%for product in products %}
    <a href="{%url 'products:product_details' product.id %}" class="block w-[270px] shadow  p-[10px]">
        <img alt="" src="{{product.image.url}}" class=" w-full h-[200px] object-cover " />

        <h3 class="mt-4 text-lg font-bold text-gray-900 sm:text-xl">{{product.name}}</h3>

        <p class="mt-2 max-w-sm text-gray-700">
            <span class="text-[#DB4444]">{{product.price}}$</span> <del>{{product.alternatePrice}}$</del>
        </p>
        <p>
            <i class="fa-solid fa-star text-[#FFAD33]"></i>
            <i class="fa-solid fa-star text-[#FFAD33]"></i>
            <i class="fa-solid fa-star text-[#FFAD33]"></i>
            <i class="fa-solid fa-star text-[#FFAD33]"></i>
            <i class="fa-solid fa-star text-[#FFAD33]"></i>
        </p>
       
    </a>
    {% endfor %}
    {% endblock %}

</div>

ecommerce/products/templates/components/header.html
<header class="shadow-md">
    <div class="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 items-center justify-between">
            <div class="md:flex md:items-center md:gap-12">
                <a class="block text-teal-600" href="/home">
                    <span class="sr-only">Home</span>
                    <img src="logo.png" alt="...">
                </a>
            </div>

            <div class="hidden md:block">
                <nav aria-label="Global">
                    <ul class="flex items-center gap-6 text-sm">
                        <li>
                            <a class="text-gray-500 transition hover:text-gray-500/75" href="/home"> Home </a>
                        </li>


                    </ul>
                </nav>
            </div>

            <div class="flex items-center gap-4">
                <div class="sm:flex sm:gap-4">
                    <a class="rounded-md  px-5 py-2.5 text-sm font-medium " href="/cart">
                        <i class="fa-solid fa-cart-shopping"></i>
                    </a>

                 
                </div>

                <div class="block md:hidden">
                    <button class="rounded p-2  transition ">
                        <svg xmlns="http://www.w3.org/2000/svg" class="size-5" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </div>
</header>

ecommerce/products/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body class="bg-[#F5F5F5]">
    {%include "components/header.html"%}
    {%include "components/card.html"%}









</body>

</html>

ecommerce/products/templates/productDetails.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.tailwindcss.com"></script>



</head>

<body class="bg-[#F5F5F5]">

    {%include "components/header.html"%}


    <div class="flex flex-wrap   gap-[20px] items-center">

        <div class="left  flex gap-[10px]">

            <div class="two  flex flex-col justify-between">
                <img src="{{product.image.url}}" alt="..." class="w-[200px]">
                <img src="{{product.image.url}}" alt="..." class="w-[200px]">
            </div>
            <div class="one">
                <img src="{{product.image.url}}" alt="" class="w-[400px] h-[400px]">
            </div>
        </div>


        <div class="right">


            <h2>{{product.name}} </h2>
            <p>
                <i class="fa-solid fa-star text-[#FFAD33]"></i>
                <i class="fa-solid fa-star text-[#FFAD33]"></i>
                <i class="fa-solid fa-star text-[#FFAD33]"></i>
                <i class="fa-solid fa-star text-[#FFAD33]"></i>
                <i class="fa-solid fa-star text-[#FFAD33]"></i>
            </p>
            <p>{{product.price}}</p>
            <p>{{product.desciption}}</p>
            <h3>Sizes</h3>

            <div class="flex gap-[10px] mt-[20px]">
                <span
                    class="border-[1px] border-black border-solid p-1 w-[30px] h-[30px] flex justify-center items-center rounded-[5px]">XS</span>
                <span
                    class="border-[1px] border-black border-solid p-1 w-[30px] h-[30px] flex justify-center items-center rounded-[5px]">S</span>
                <span
                    class="border-[1px] border-black border-solid p-1 w-[30px] h-[30px] flex justify-center items-center rounded-[5px]">M</span>
                <span
                    class="border-[1px] border-black border-solid p-1 w-[30px] h-[30px] flex justify-center items-center rounded-[5px]">L</span>
                <span
                    class="border-[1px] border-black border-solid p-1 w-[30px] h-[30px] flex justify-center items-center rounded-[5px]">XL</span>

            </div>




            <div class="flex flex-wrap   gap-[10px] justify-between items-center mt-[20px]">

<!-- 
                <div class="w-[250px] max-w-sm relative ">
                    <div class="relative">
                        <button id="decreaseButton"
                            class="absolute right-9 top-1 rounded bg-slate-800 p-1.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
                            type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                class="w-4 h-4">
                                <path d="M3.75 7.25a.75.75 0 0 0 0 1.5h8.5a.75.75 0 0 0 0-1.5h-8.5Z" />
                            </svg>
                        </button>
                        <input id="amountInput" type="number" value="0"
                            class="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md pl-3 pr-20 py-2 transition duration-300 ease focus:outline-none focus:border-slate-400 hover:border-slate-300 shadow-sm focus:shadow appearance-none [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none" />
                        <button id="increaseButton"
                            class="absolute right-1 top-1 rounded bg-slate-800 p-1.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
                            type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                class="w-4 h-4">
                                <path
                                    d="M8.75 3.75a.75.75 0 0 0-1.5 0v3.5h-3.5a.75.75 0 0 0 0 1.5h3.5v3.5a.75.75 0 0 0 1.5 0v-3.5h3.5a.75.75 0 0 0 0-1.5h-3.5v-3.5Z" />
                            </svg>
                        </button>
                    </div>

                </div>

                <script>
                    // Select the elements
                    const amountInput = document.getElementById('amountInput');
                    const increaseButton = document.getElementById('increaseButton');
                    const decreaseButton = document.getElementById('decreaseButton');

                    // Increase the value
                    increaseButton.addEventListener('click', () => {
                        amountInput.value = parseInt(amountInput.value) + 1;
                    });

                    // Decrease the value and prevent going below 0
                    decreaseButton.addEventListener('click', () => {
                        amountInput.value = Math.max(0, parseInt(amountInput.value) - 1);
                    });
                </script> -->



                <a class="inline-block rounded border border-[#DB4444] h-fit bg-[#DB4444] px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-[#DB4444] focus:outline-none focus:ring active:text-[#DB4444]"
                    href="{% url 'products:add_product' product.id %}">
                    Buy Now
                </a>

            </div>


        </div>

    </div>

    {%include "components/card.html"%}






</body>

</html>